{
  pkgs,
  pkgs-stable,
  ...
}: {
  programs.alacritty.enable = true;

  programs.obs-studio = {
    enable = true;
    plugins = with pkgs.obs-studio-plugins; [
      obs-backgroundremoval
      obs-pipewire-audio-capture
      obs-gstreamer
    ];
  };

  home.packages = with pkgs; [
    i7z
    age
    alcom
    appimage-run
    android-tools
    anki
    blockbench
    blueman
    blender
    calibre
    chromium
    vesktop
    distrobox
    drawio
    vscode
    cmus
    direnv
    darkplaces
    dbeaver-bin
    ericw-tools
    fastfetch
    faugus-launcher
    ffmpeg
    flameshot
    freenect
    element-desktop
    gcc
    gimp
    gnumake
    gnutar
    grim
    gvfs
    guile
    guile-hoot
    guile-reader
    guile-lib
    guile-hall
    guile-commonmark
    guix
    gurobi
    haunt
    gzdoom
    htop
    i3status
    imagemagick
    imv
    inkscape
    ironwail
    jack2
    jetbrains.idea-oss
    jetbrains.pycharm-oss
    jetbrains.webstorm
    kdePackages.kdenlive
    libreoffice-still
    mpv
    nethack
    nicotine-plus
    p7zip
    python3
    networkmanagerapplet
    obsidian
    octave
    openal
    openarena
    openttd
    openvpn
    orca-slicer
    packwiz
    pandoc
    pavucontrol
    pkg-config
    pkgs-stable.bottles
    pkgs-stable.wineWow64Packages.staging
    pkgs-stable.winetricks
    umu-launcher
    pkgs-stable.steam-run
    playerctl
    ppsspp
    prismlauncher
    qbittorrent
    qemu
    qgis
    qmmp
    quakespasm
    quickemu
    r2mod_cli
    rtabmap
    reaper
    (retroarch.withCores (cores:
      with cores; [
        flycast
        beetle-gba
        desmume
        dolphin
        citra
        dosbox
        mesen
        snes9x
        pcsx2
      ]))
    slurp
    ssh-to-age
    strawberry
    sops
    super-productivity
    teams-for-linux
    telegram-desktop
    thunderbird
    tmux
    tree
    ttyper
    typst
    localsend
    unityhub
    unrar
    unzip
    virt-manager
    vscode
    wdisplays
    wike
    wl-clipboard
    xarchiver
    (thunar.override {
      thunarPlugins = [
        thunar-archive-plugin
        thunar-volman
        thunar-media-tags-plugin
      ];
    })
    xonotic-glx
    xournalpp
    xsel
    xz
    zip
    zotero
  ];
}
